### ISSUE TITLE
Bump new version for RN 0.40.0

### ISSUE THREAD

**Issue by yyoshiki41** [mehcode/rn-ios-user-agent#2]
I would like you to publish new version that has below commit.
https://github.com/mehcode/rn-ios-user-agent/pull/1
Sorry to bother you.

Thanks!

**Comment by yyoshiki41** [comment]
@mehcode
Are you still supporting this lib?

**Comment by mehcode** [comment]
@yyoshiki41 Released as 1.0.0.

---

Sorry this took so long. My projects were using git urls to link to this so I didn't notice it not being released.

**Comment by yyoshiki41** [comment]
@mehcode 

Sorry to bother you.
Thanks!!
