### ISSUE TITLE
Support RN 0.60 ++

### ISSUE THREAD

**Issue by Foskas** [mehcode/rn-ios-user-agent#3]
Hi!

Do you have any plans for RN 0.60+ support?

Thanks.

**Comment by mehcode** [comment]
I'll merge a PR.

**Comment by iLevye** [comment]
I did a pull request but didn't mention this issue. I just saw this thread after pull request.

**Comment by mehcode** [comment]
Released your PR as v2.0.0

Thanks for the bump :)
